// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package pbtester is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Person
	AddressBook
*/
package pbtester

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name             *string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id               *int32                `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email            *string               `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones           []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=pbtester.Person_PhoneType" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People           []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "pbtester.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "pbtester.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "pbtester.AddressBook")
	proto.RegisterEnum("pbtester.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x48, 0x2a, 0x49, 0x2d, 0x2e, 0x49, 0x2d,
	0x52, 0xba, 0xca, 0xc8, 0xc5, 0x16, 0x90, 0x5a, 0x54, 0x9c, 0x9f, 0x27, 0xc4, 0xc3, 0xc5, 0x92,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x29, 0xc4, 0xc5, 0xc5, 0x94, 0x99, 0x22,
	0xc1, 0x04, 0x64, 0xb3, 0x0a, 0xf1, 0x72, 0xb1, 0xa6, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0x30, 0x83,
	0xa5, 0x74, 0xb8, 0xd8, 0x0a, 0x32, 0xf2, 0xf3, 0x52, 0x8b, 0x25, 0x58, 0x14, 0x98, 0x35, 0xb8,
	0x8d, 0x64, 0xf4, 0x60, 0xc6, 0xe9, 0x41, 0x8c, 0xd2, 0x0b, 0x00, 0x49, 0xfb, 0x95, 0xe6, 0x26,
	0xa5, 0x16, 0x49, 0xb9, 0x73, 0x71, 0x23, 0x71, 0x85, 0xf8, 0xb8, 0xd8, 0xf2, 0xc0, 0x2c, 0xa8,
	0x3d, 0x1a, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x60, 0x9b, 0xf8, 0x8c, 0xa4, 0xb0, 0x1b, 0x15,
	0x02, 0x54, 0xa1, 0xa4, 0xcd, 0xc5, 0x09, 0xe7, 0x00, 0x9d, 0xc7, 0xe6, 0xeb, 0xef, 0xe4, 0xe9,
	0xe3, 0x2a, 0xc0, 0x20, 0xc4, 0xc1, 0xc5, 0xe2, 0xe1, 0xef, 0xeb, 0x2a, 0xc0, 0x08, 0x62, 0x85,
	0xfb, 0x07, 0x79, 0x0b, 0x30, 0x29, 0xe9, 0x73, 0x71, 0x3b, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17,
	0x3b, 0xe5, 0xe7, 0x67, 0x0b, 0x29, 0x00, 0x9d, 0x9c, 0x9a, 0x5f, 0x90, 0x03, 0xf2, 0x1d, 0xc8,
	0xc9, 0x02, 0xe8, 0xf6, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xb4, 0x2d, 0xe6, 0x1f, 0x01,
	0x00, 0x00,
}
